### ISSUE TITLE
Schedule save API takes between 3 and 7 seconds

### ISSUE THREAD

**Issue by ti2ger92** [UPchieve/server#189]
The API at the code index takes from 3 to 7 seconds or more to invoke both on local and production instances.

https://github.com/UPchieve/server/blob/3c716f73de0aaff49c646e4faaf1d424b8f49080/router/api/calendar.js#L4

Adhoc experiments seem to show some time taken with database save operations, but also a lot of time is taken before the API is invoked at all. This is far too long and creates a bad user experience.

**Comment by jkeat** [comment]
Note: before reaching the `/calendar/save` route handler, the request goes through the passport middleware and fetches the user object

https://github.com/UPchieve/server/blob/6fb6df6ce59831ebc696b079ac86038777d5b7f8/router/auth/passport.js#L10
