### ISSUE TITLE
Updating calendar availability and timezone calls passport middleware twice

### ISSUE THREAD

**Issue by dmnisson** [UPchieve/server#214]
Right now the action of clicking "Save" in the calendar view updates the availability and timezone, requiring calls to two separate API endpoints (`/api/calendar/save` and `/api/calendar/tz/save`). Both of these requests must be processed through the passport middleware, significantly affecting performance. In addition, the Mongoose `save` function is called twice (once for each endpoint) resulting in two separate database queries. Using a single API endpoint and a single call to the `save` function to perform both of these actions would significantly improve performance, in addition to the improvement created by https://github.com/UPchieve/server/pull/207.

**Comment by jkeat** [comment]
Resolved by https://github.com/UPchieve/server/pull/218
