### ISSUE TITLE
Missing high school seed data

### ISSUE THREAD

**Issue by jkeat** [UPchieve/server#265]
Need to add seed data for high schools and import it in `init.js`. At least one of the seed high schools should have `isApproved` set to true (and at least one false).

Also, need to add README instructions for full import; need to run:
`node dbutils/import-zip-codes.js`

**Comment by ti2ger92** [comment]
The loaded schools allow the e2e tests to get further, but not pass. I think perhaps entries in the Zip Code collection are also needed to accomplish this.

@jkeat , perhaps you can add language about the full import util. I don't think it should be something Github community members should need to worry about, so maybe it can be in its own section? I think anything a Github community member needs to run basic tests should load automatically with one of our setup scripts.
