### ISSUE TITLE
Only use "moment-timezone", remove "moment" as a dependency

### ISSUE THREAD

**Issue by jkeat** [UPchieve/server#341]
https://stackoverflow.com/questions/49729646/using-both-moment-and-moment-tz

> Remove moment as a separate package in your package.json and reference moment-timezone whenever you need an instance of the moment object. In fact, if you don't and you're referencing both packages separately, you'll be loading two largely identical versions of moment.

> The documentation referenced by @RobG in his comment is correct, it's just that the moment-timezone package itself loads moment as a dependency.

**Comment by ti2ger92** [comment]
@jkeat , this appears to be already complete. Do you agree?

**Comment by jkeat** [comment]
@ti2ger92 yep looks like it!
