### ISSUE TITLE
Rewrite Readme to Dockerize Mongo

### ISSUE THREAD

**Issue by ti2ger92** [UPchieve/server#359]
Currently the Readme file suggests using asdf to install Mongo. A Docker install is an easier and more portable effort. This can be used, now that we no longer rely on Mongo native libraries to install seed data.

The Readme should be rewritten to no longer emphasize Mongo as an asdf module, but instead have a copy-paste-able command to run a mongo image with a local volume. The Mongo asdf can remain as an alternative (if folks do not want docker).

**Comment by austinhallock** [comment]
IMO this is a good idea. Docker is more ubiquitous than asdf. This is what I do for my local dbs

Mongo:
`docker run -i --rm --name mongodb -p 27017-27019:27017-27019 -v /data/db:/data/db mongo:4.0.16`

Redis: `docker run -i --rm --name redis -p 6379:6379 -v /data:/data -t redis:3.2.0`

**Comment by jkeat** [comment]
Sounds good to me 👍

**Comment by ti2ger92** [comment]
> IMO this is a good idea. Docker is more ubiquitous than asdf. This is what I do for my local dis

Hey actually, do we have the architecture such that Redis tries to directly call Mongo? If so, we'll need to use Docker network ID's for Mac's (and probably windows machines), because Docker runs as a VM on those systems. As long as web, running in non-docker, calls them directly, we're fine.
