### ISSUE TITLE
Unused middleware

### ISSUE THREAD

**Issue by jkeat** [UPchieve/server#382]
We should audit our middleware and remove what's unused

For example, I don't think `connect-busboy` is being used

**Comment by ti2ger92** [comment]
other middleware:
`@sentry/node`: used many places like [this](https://github.com/UPchieve/server/blob/122196ba1a56499f9493404f9527a8e8ecd66c57/controllers/SessionCtrl.js#L4)
`logger('dev')`: required logger
`bodyParser`: `body-parser` is altering each incoming request, which seems important.
`cors`:allows cors, seems important
`promisifyLogin`: does what it says, and is needed, though it could be be moved inline.
`@small-tech/express-ws`: is used [here](https://github.com/UPchieve/server/blob/122196ba1a56499f9493404f9527a8e8ecd66c57/router/whiteboard/index.ts#L221).

**Comment by jkeat** [comment]
Resolved by https://github.com/UPchieve/server/pull/420
