### ISSUE TITLE
Feedback no longer showing up in database?

### ISSUE THREAD

**Issue by alymurray** [UPchieve/server#41]
This one is really weird. It used to show up as a collection in mongo but no longer is showing up?

![image](https://user-images.githubusercontent.com/20755642/45965707-37469500-bff7-11e8-90f5-a7df34191e7d.png)

**Comment by jmromer** [comment]
This appears to have been resolved:

```
> show collections
auth-sessions
feedbacks
. . . 
```
```
> db.feedbacks.count()
31
```
