### ISSUE TITLE
New sessions don't get listed when the topic is "Applications"

### ISSUE THREAD

**Issue by lualparedes** [UPchieve/server#49]
"It might be an issue related to changing plurality. Essays may not work either."

**Comment by jmromer** [comment]
Closing as fixed:

<img width="1215" alt="Screen Shot 2019-03-25 at 9 59 26 PM" src="https://user-images.githubusercontent.com/4433943/54966013-475d1400-4f49-11e9-95e8-d8acb40feabe.png">


![Uploading Screen Shot 2019-03-25 at 9.59.26 PM.png…]()
