### ISSUE TITLE
Use a for loop in CalendarCtrl.js line 7

### ISSUE THREAD

**Issue by ilakumar** [UPchieve/server#8]
Update CalendarCtrl.js based on a suggestion from @stackptr (requires structural reworking of the availability object)

See the suggestion below for line 7 of CalendarCtrl.js:

Would've been a good use for a for loop!

```
const times = [ '12a', '1a', '2a', ..., '11p']
const days = ['Sunday', ... 'Saturday']
const availability = days.map( day => ({
  [day]: times.map( time => ({ [time]: false })
})
)
```

Basically, map over the list of day names, and for each day then map over the list of all possible times. In both maps, we can put the mapped value as a key in an object by `[]`

So the following:
```
const myValue = 'x'`
const myObj = { [myValue]: false }
```

... will result in:

```
console.log(myObject) // {x: false}
```

**Comment by jmromer** [comment]
Closing as stale — feel free to re-open with added details if needed thanks! 😄
